version: "3.9"

services:
  postgres:
      container_name: postgres
      image: postgres:latest
      command:
        - "postgres"
        - "-c"
        - "max_connections=50"
        - "-c"
        - "shared_buffers=1GB"
        - "-c"
        - "effective_cache_size=4GB"
        - "-c"
        - "work_mem=16MB"
        - "-c"
        - "maintenance_work_mem=512MB"
        - "-c"
        - "random_page_cost=1.1"
        - "-c"
        - "temp_file_limit=10GB"
        - "-c"
        - "log_min_duration_statement=200ms"
        - "-c"
        - "idle_in_transaction_session_timeout=10s"
        - "-c"
        - "lock_timeout=1s"
        - "-c"
        - "statement_timeout=60s"
        - "-c"
        - "shared_preload_libraries=pg_stat_statements"
        - "-c"
        - "pg_stat_statements.max=10000"
        - "-c"
        - "pg_stat_statements.track=all"
      environment:
        POSTGRES_DB: "tg_game"
        POSTGRES_USER: "tg_user"
        POSTGRES_PASSWORD: "tg_password"
      ports:
        - 15432:5432
      networks:
        - my-bridge
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U tg_user -d tg_game"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
      restart: unless-stopped
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 4G

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "ebcscp2@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - /multy_serv_vol/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - my-bridge
    depends_on:
      - postgres

  rabbitmq:
    container_name: rabbitmq
    build: poller/rabbit/
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=tg_user
      - RABBITMQ_DEFAULT_PASS=tg_password
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - my-bridge
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5672"]
        interval: 30s
        timeout: 10s
        retries: 5

  # admin:
  #   container_name: admin
  #   build: admin/
  #   ports:
  #       - 8080:8080
  #   depends_on:
  #     postgres:
  #         condition: service_healthy
  #   volumes:
  #     - /multy_serv_vol/configs:/home/admin/configs
  #   #command: alembic upgrade head
  #   command: python main.py
  #   networks:
  #     - my-bridge
      
  poller:
    container_name: poller
    build: poller/
    # depends_on:
    #     rabbitmq:
    #       condition: service_healthy
        # postgres:
        #   condition: service_healthy  
    #volumes:
    #  - /multy_serv_vol/configs:/home/poller/configs    
    command: python main.py
    networks:
      - my-bridge 

  worker:
    container_name: worker
    build: worker/
    # depends_on:
    #     rabbitmq:
    #       condition: service_healthy
      # postgres:
      #     condition: service_healthy  
    #volumes:
     # - /multy_serv_vol/configs:/home/worker/configs
    command: python main.py
    networks:
      - my-bridge       

networks:
  my-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.45.0/24
