bot:
  api_path: https://api.telegram.org/bot
  token: 5603173084:AAHWD4jOUnbCbs_XLIPQ8OS4kamd2owOOpI
  id:
rabbitmq:
  queue_name:  tg_bot
  exchange_name: bot_exchange
  rabbit_url: amqp://tg_user:tg_password@rabbitmq:5672/