"""Added question/answer table

Revision ID: 11615b4bf692
Revises: 94293b931833
Create Date: 2023-03-02 17:18:33.777515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11615b4bf692'
down_revision = '94293b931833'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
