"""Added question/answer table

Revision ID: 94293b931833
Revises: f679cd6eb5e3
Create Date: 2023-03-02 17:07:18.058111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94293b931833'
down_revision = 'f679cd6eb5e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
