"""Added question/answer table

Revision ID: f679cd6eb5e3
Revises: b8c3b31e7e63
Create Date: 2023-03-02 17:01:58.980196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f679cd6eb5e3'
down_revision = 'b8c3b31e7e63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
