database:
  host: localhost #postgres
  port: 5432
  user: tg_user
  password: tg_password
  database: tg_game
  base_url: postgresql+asyncpg://tg_user:tg_password@localhost/tg_game
bot:
  api_path: https://api.telegram.org
  token: 5603173084:AAHWD4jOUnbCbs_XLIPQ8OS4kamd2owOOpI
  id: 5603173084
rabbitmq:
  queue_name:  tg_bot
  exchange_name: bot_exchange
  rabbit_url: amqp://tg_user:tg_password@localhost:5672/