database:
  host: postgres #postgres
  port: 5432
  user: tg_user
  password: tg_password
  database: tg_game
  base_url: postgresql+asyncpg://tg_user:tg_password@postgres/tg_game
bot:
  api_path: https://api.telegram.org
  token: 5603173084:AAHWD4jOUnbCbs_XLIPQ8OS4kamd2owOOpI
  id: 1079223049
rabbitmq:
  queue_name:  tg_bot
  exchange_name: bot_exchange
  rabbit_url: amqp://tg_user:tg_password@rabbitmq:5672/
game:
  user: 6
  questions: 11  