FROM python:3.9-alpine

RUN adduser -D admin	
WORKDIR /home/admin

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app app
COPY alembic alembic
COPY configs configs
COPY alembic.ini main.py  ./

USER admin
