bot:
  api_path: https://api.telegram.org/bot
  token: 6291132929:AAGe2sRTPRxG6WLWn0RqQmi-8mFqYXuUWZM 
  id:
rabbitmq:
  queue_name:  tg_bot
  exchange_name: bot_exchange
  rabbit_url: amqp://tg_user:tg_password@rabbitmq:5672/